// @ts-check

// This runs in Node.js - Don't use client-side code here (browser APIs, JSX...)

/**
 * Creating a sidebar enables you to:
 - create an ordered group of docs
 - render a sidebar for each doc of that group
 - provide next/previous navigation

 The sidebars can be generated from the filesystem, or explicitly defined here.

 Create as many sidebars as you want.

 @type {import('@docusaurus/plugin-content-docs').SidebarsConfig}
 */
const sidebars = {
  // Reorganizing the sidebar to follow the specified learning sequence:
  // Intro → Module 1 → Module 2 → Module 3 → Module 4.
  // Tutorial-related content will be addressed in a subsequent task.
  tutorialSidebar: [
    'intro', // Corresponds to docs/intro.md
    {
      type: 'category',
      label: 'Module 1: ROS 2', // Based on folder name and common understanding
      items: [{ type: 'autogenerated', dirName: '001-ros2-module1' }], // Auto-generates items from the 'docs/001-ros2-module1' directory
    },
    {
      type: 'category',
      label: 'Module 2: Digital Twin',
      items: [{ type: 'autogenerated', dirName: '002-digital-twin-module' }],
    },
    {
      type: 'category',
      label: 'Module 3: AI Robot Brain (Isaac)',
      items: [{ type: 'autogenerated', dirName: '003-ai-robot-brain-isaac' }],
    },
    {
      type: 'category',
      label: 'Module 4: VLA Robot Brain',
      items: [{ type: 'autogenerated', dirName: '004-vla-robot-brain' }],
    },
  ],
};

export default sidebars;
